### ISSUE TITLE
FEAT: Add testing library

### ISSUE THREAD

**Issue by fajfara** [Shoppingify/frontend#66]
I have never done any testing with any library or framework (jest or similar). I think it would be cool if we add this as well. I had the idea of adding [jest](https://jestjs.io/) or/and [react testing library,](https://testing-library.com/docs/react-testing-library/intro) but if you have a preference fire away :)

**Comment by ips-coding-challenge** [comment]
You read my mind. I never add tests for the frontend and already for my last challenge, I said that I should start to test the frontend. So yes, completely in for that because when you start to add "step to reproduce" to the issues, it's a sign that we should add some tests :D. There is cypress also which is apparently well known.
